### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by romainmartinez** [pyomeca/pyomeca#6]
# Near-term
- [x] read c3d files (integrate btk in pyomeca)

# Medium-term
- [x] wrap btk in pyomeca
- [ ] implement automatic tests ([guide](http://docs.python-guide.org/en/latest/writing/tests/))
- [ ] package pyomeca ([guide](https://packaging.python.org/tutorials/distributing-packages/))
- [ ] setup docs ([readthedocs guide](http://docs.readthedocs.io/en/latest/getting_started.html))

# Long-term
- [ ] OpenSim wrapper

**Comment by romainmartinez** [comment]
Moved to [project](https://github.com/orgs/pyomeca/projects)
